# Generated by Django 5.2.1 on 2025-05-16 05:55

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع')),
                ('message', django_ckeditor_5.fields.CKEditor5Field(verbose_name='متن پیام')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('created', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, verbose_name='معرفی')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='تلفن')),
                ('mobile', models.CharField(blank=True, max_length=12, verbose_name='همراه')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='نشانی')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/core', verbose_name='لوگو')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='uploads/core', verbose_name='فاوآیکون')),
                ('about', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='درباره ما')),
                ('contact', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='تماس با ما')),
                ('created', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'پیکربندی',
                'verbose_name_plural': 'پیکربندی',
            },
        ),
    ]
