# Generated by Django 5.2.1 on 2025-05-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created',), 'verbose_name': 'دسته', 'verbose_name_plural': 'دسته\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': 'دیدگاه', 'verbose_name_plural': 'دیدگاه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',), 'verbose_name': 'نوشته', 'verbose_name_plural': 'نوشته\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-created',), 'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب\u200cها'},
        ),
    ]
