# Generated by Django 5.2.1 on 2025-05-20 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('created', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.post', verbose_name='نوشته')),
            ],
            options={
                'verbose_name': 'پسند',
                'verbose_name_plural': 'پسندها',
                'ordering': ('created',),
                'unique_together': {('session_key', 'post')},
            },
        ),
    ]
